chatsTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    TableName: chatsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH